import { useState } from 'react';
import { Columns2, Layers3, Contrast, MoveUpRight, Crosshair } from 'lucide-react';
import { artifactUrl, type RegistrationResult, type MatchPoint } from '../lib/api';
type Mode='split'|'blend'|'difference'|'vectors';
const PointImage=({src,width,height,points,kind,selected}:{src?:string;width:number;height:number;points:MatchPoint[];kind:'source'|'reference';selected:number|null})=><div className="flex min-h-0 min-w-0 items-center justify-center overflow-hidden bg-black" data-testid={`${kind}-image-panel`}>
  <svg viewBox={`0 0 ${width} ${height}`} className="h-full w-full" preserveAspectRatio="xMidYMid meet" data-testid={`${kind}-image-plane`}>
    {src&&<image href={src} width={width} height={height} preserveAspectRatio="none" data-testid={`${kind}-viewport-image`}/>}
    {points.map(point=><circle key={point.index} cx={kind==='source'?point.source_x:point.reference_x} cy={kind==='source'?point.source_y:point.reference_y} r={Math.max(width,height)/180} fill="none" stroke={selected===point.index?'#fff':point.status==='inlier'?'#f2c56e':'#ee919a'} strokeWidth={selected===point.index?2:1} vectorEffect="non-scaling-stroke" data-testid={`${kind}-marker-${point.index}`}/>)}
  </svg>
</div>;
export const InspectionViewport=({run,sourcePreview,referencePreview,selected}:{run:RegistrationResult|null;sourcePreview:string|null;referencePreview?:string;selected:number|null})=>{
  const [mode,setMode]=useState<Mode>('split'); const [opacity,setOpacity]=useState(.5);const [showPoints,setShowPoints]=useState(true);
  const hasSolution=!!run?.metrics;const displayReady=hasSolution||run?.status==='failed'&&!!run.source_metadata;
  const source=displayReady?artifactUrl(run!.source_url):sourcePreview||undefined;
  const reference=displayReady?artifactUrl(run!.reference_url):referencePreview;
  const registered=hasSolution?artifactUrl(run!.preview_url):undefined;
  const points=showPoints?(run?.match_points||[]):[];
  const width=run?.reference_width||1024,height=run?.reference_height||768;
  return <section className="panel-card overflow-hidden" data-testid="registration-viewport-panel">
    <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-800 px-4 py-3"><div><p className="eyebrow" data-testid="viewport-eyebrow">04 / INSPECT</p><h2 className="section-title" data-testid="viewport-title">Image comparison</h2></div><div className="flex flex-wrap gap-1" data-testid="registration-mode-controls">{([{id:'split',label:'Split',icon:Columns2},{id:'blend',label:'Blend',icon:Layers3},{id:'difference',label:'Diff',icon:Contrast},{id:'vectors',label:'Vectors',icon:MoveUpRight}] as const).map(({id,label,icon:Icon})=><button key={id} onClick={()=>setMode(id)} disabled={id!=='split'&&!hasSolution} aria-pressed={mode===id} className={`view-mode-btn disabled:opacity-40 ${mode===id?'view-mode-active':''}`} data-testid={`registration-mode-${id}-btn`}><Icon size={13}/>{label}</button>)}</div></div>
    <div className="p-3"><div className={`registration-viewport mode-${mode}`} data-testid="registration-viewport">
      {!source&&!reference?<div className="absolute inset-0 flex flex-col items-center justify-center gap-3 px-6 text-center"><Crosshair className="text-slate-600" size={32}/><p className="text-sm text-slate-400" data-testid="viewport-empty-title">Awaiting source and reference</p><p className="text-xs text-slate-500" data-testid="viewport-empty-help">No registration evaluated</p></div>:mode==='split'?<div className="grid h-full grid-cols-2 gap-px bg-slate-700" data-testid="split-view"><PointImage src={source} width={run?.source_width||1024} height={run?.source_height||768} points={points} kind="source" selected={selected}/><PointImage src={reference} width={width} height={height} points={points} kind="reference" selected={selected}/></div>:<div className="relative h-full w-full bg-black" data-testid={`${mode}-view`}>
        <svg viewBox={`0 0 ${width} ${height}`} className="h-full w-full" preserveAspectRatio="xMidYMid meet" data-testid="comparison-image-plane"><image href={reference} width={width} height={height} preserveAspectRatio="none" data-testid="reference-overlay-image"/>{mode!=='vectors'&&<image href={registered} width={width} height={height} preserveAspectRatio="none" style={{opacity:mode==='blend'?opacity:1,mixBlendMode:mode==='difference'?'difference':'normal'}} data-testid="registered-overlay-image"/>}{mode==='vectors'&&points.filter(p=>p.status==='inlier').map(p=><g key={p.index} data-testid={`residual-vector-${p.index}`}><line x1={p.predicted_x} y1={p.predicted_y} x2={p.reference_x} y2={p.reference_y} stroke={selected===p.index?'#fff':'#f2c56e'} strokeWidth={2} vectorEffect="non-scaling-stroke"/><circle cx={p.reference_x} cy={p.reference_y} r={width/250} fill="#7dd3db"/></g>)}</svg>
        {mode==='blend'&&<label className="absolute bottom-4 right-4 w-36 bg-black/80 p-2 text-[10px] text-slate-300" data-testid="blend-opacity-control">Opacity {Math.round(opacity*100)}%<input type="range" min={0} max={1} step={.01} value={opacity} onChange={e=>setOpacity(+e.target.value)} className="range-amber w-full" aria-label="Blend opacity" data-testid="blend-opacity-input"/></label>}
        {mode==='difference'&&<p className="absolute bottom-3 left-3 bg-black/80 p-2 text-[10px] text-slate-300" data-testid="difference-legend">Intensity difference · not positional accuracy</p>}
      </div>}
      {mode==='split'&&(source||reference)&&<div className="pointer-events-none absolute inset-x-0 top-0 grid grid-cols-2 text-[9px] font-mono"><span className="m-2 w-fit bg-black/80 px-2 py-1 text-amber-200" data-testid="source-image-label">SOURCE · MOVING</span><span className="m-2 w-fit bg-black/80 px-2 py-1 text-cyan-200" data-testid="reference-image-label">REFERENCE · FIXED</span></div>}
    </div><div className="mt-3 flex flex-wrap justify-between gap-2 text-[10px] text-slate-500" data-testid="viewport-footer"><span data-testid="viewport-dimensions">{hasSolution?`${run!.source_width} × ${run!.source_height} → ${width} × ${height} px`:'Pixel coordinates · no assumed lunar CRS'}</span><label className="flex items-center gap-2"><input type="checkbox" checked={showPoints} onChange={e=>setShowPoints(e.target.checked)} data-testid="toggle-match-points"/>Match points</label></div></div>
  </section>;
};