import { useEffect, useState } from 'react';
import { toast } from 'sonner';
import { Button } from './ui/button';
import { apiPut,apiPost, type RegistrationResult, type Thresholds } from '../lib/api';
import { GateSummary } from './ResultsPanel';
export const QualityControls=({run,onUpdate,onAdjustment}:{run:RegistrationResult|null;onUpdate:(run:RegistrationResult)=>void;onAdjustment:(run:RegistrationResult)=>void})=>{
 const [limits,setLimits]=useState<Thresholds|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [x,setX]=useState(0);const [y,setY]=useState(0);const [checkpointFile,setCheckpointFile]=useState<File|null>(null);const [provenance,setProvenance]=useState('');const [independent,setIndependent]=useState(false);
 useEffect(()=>{setLimits(run?.thresholds||null);setError('');},[run?.id,run?.thresholds]);
 const action=async(operation:()=>Promise<void>)=>{setBusy(true);setError('');try{await operation();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const save=()=>action(async()=>{if(run&&limits){onUpdate(await apiPut<RegistrationResult>(`/registration/runs/${run.id}/thresholds`,limits));toast.success('Server checks recomputed');}});
 const adjust=()=>action(async()=>{if(run)onAdjustment(await apiPost<RegistrationResult>(`/registration/runs/${run.id}/adjust`,{offset_x:x,offset_y:y}));});
 const checkpoints=()=>action(async()=>{if(!run||!checkpointFile)return;if(checkpointFile.size>100000)throw new Error('Checkpoint JSON must be under 100 KB.');const points=JSON.parse(await checkpointFile.text());onUpdate(await apiPost<RegistrationResult>(`/registration/runs/${run.id}/checkpoints`,{points,provenance,independent}));toast.success('Independent-checkpoint residuals evaluated');});
 return <section className="panel-card" data-testid="quality-thresholds-panel"><p className="eyebrow" data-testid="quality-eyebrow">07 / ACCEPTANCE</p><h2 className="section-title mb-3" data-testid="quality-thresholds-heading">Quality gate</h2><p className="text-[10px] leading-5 text-slate-500" data-testid="threshold-policy-note">Provisional server policy · limits may be tightened, never bypassed.</p><GateSummary run={run}/>
 {run?.status==='completed'&&limits&&<><details className="mt-4 border-t border-slate-800 pt-3" data-testid="threshold-controls-details"><summary className="cursor-pointer text-xs text-cyan-200" data-testid="threshold-controls-trigger">Acceptance limits</summary><div className="mt-4 space-y-3">{([{key:'min_inliers',label:'Min inliers',step:1,min:20,max:10000,unit:'points'},{key:'min_inlier_ratio',label:'Min inlier ratio',step:.05,min:.5,max:1,unit:'0–1'},{key:'max_rmse',label:'Max fitting RMSE',step:.05,min:.001,max:1.5,unit:'px'},{key:'min_overlap',label:'Min valid overlap',step:.05,min:.2,max:1,unit:'0–1'},{key:'min_coverage',label:'Min coverage',step:.05,min:.25,max:1,unit:'0–1'},{key:'max_checkpoint_rmse',label:'Max checkpoint RMSE',step:.1,min:.001,max:2,unit:'px'}] as const).map(field=><label className="flex items-center justify-between gap-2 text-[10px] text-slate-400" key={field.key}>{field.label}<span className="flex items-center gap-2"><input type="number" value={limits[field.key]} min={field.min} max={field.max} step={field.step} onChange={e=>setLimits({...limits,[field.key]:+e.target.value})} className="w-20 rounded border border-slate-700 bg-black/20 p-2 text-right text-amber-200" data-testid={`threshold-${field.key}-input`}/>{field.unit}</span></label>)}<Button size="sm" variant="outline" className="w-full" onClick={save} disabled={busy} data-testid="save-thresholds-btn">Recompute quality gate</Button></div></details>
 <details className="mt-4 border-t border-slate-800 pt-3" data-testid="checkpoint-controls"><summary className="cursor-pointer text-xs text-cyan-200" data-testid="checkpoint-controls-trigger">Independent checkpoints</summary><div className="mt-3 space-y-3"><label className="form-field">Checkpoint JSON<input type="file" accept=".json" onChange={e=>setCheckpointFile(e.target.files?.[0]||null)} data-testid="checkpoint-file-input"/></label><a className="inline-block text-[10px] text-cyan-200" href="/checkpoint-format.json" download data-testid="checkpoint-template-link">Download format example</a><label className="form-field">Checkpoint provenance<textarea value={provenance} onChange={e=>setProvenance(e.target.value)} rows={2} data-testid="checkpoint-provenance-input"/></label><label className="flex gap-2 text-[11px] text-slate-400"><input type="checkbox" checked={independent} onChange={e=>setIndependent(e.target.checked)} data-testid="checkpoint-independent-checkbox"/>Independent of fitting correspondences</label><Button size="sm" variant="outline" className="w-full" disabled={!checkpointFile||provenance.length<10||!independent||busy} onClick={checkpoints} data-testid="evaluate-checkpoints-btn">Evaluate checkpoints</Button></div></details>
 <details className="mt-4 border-t border-slate-800 pt-3" data-testid="adjustment-controls"><summary className="cursor-pointer text-xs text-cyan-200" data-testid="adjustment-controls-trigger">Translation adjustment</summary><div className="mt-3 grid grid-cols-2 gap-3"><label className="form-field">Δx · reference px<input type="number" min={-20} max={20} step={.1} value={x} onChange={e=>setX(+e.target.value)} data-testid="adjust-x-input"/></label><label className="form-field">Δy · reference px<input type="number" min={-20} max={20} step={.1} value={y} onChange={e=>setY(+e.target.value)} data-testid="adjust-y-input"/></label></div><Button size="sm" variant="outline" className="mt-3 w-full" disabled={busy} onClick={adjust} data-testid="apply-adjustment-btn">Create re-evaluated run</Button></details>
 </>}{error&&<p role="alert" className="research-notice error-notice mt-3" data-testid="quality-action-error">{error}</p>}</section>;
};