import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { toast } from 'sonner';
import { Upload, ExternalLink, Satellite } from 'lucide-react';
import { Button } from './ui/button';
import { apiGet, apiPost, artifactUrl, type ReferenceRecord } from '../lib/api';
export const ReferenceControls=({selected,onSelect,busy}:{selected:string;onSelect:(id:string)=>void;busy:boolean})=>{
  const client=useQueryClient();const [file,setFile]=useState<File|null>(null);const [band,setBand]=useState(1);const [provenance,setProvenance]=useState('');const [uploading,setUploading]=useState(false);const [error,setError]=useState('');
  const [lat,setLat]=useState('');const [lon,setLon]=useState('');const [fetching,setFetching]=useState(false);const [autoStatus,setAutoStatus]=useState('');
  const references=useQuery({queryKey:['references'],queryFn:()=>apiGet<ReferenceRecord[]>('/catalog/references')});
  const reference=references.data?.find(r=>r.id===selected);
  const upload=async()=>{if(!file)return;setUploading(true);setError('');try{const form=new FormData();form.append('reference_image',file);form.append('band',String(band));form.append('provenance',provenance);const row=await apiPost<ReferenceRecord>('/catalog/references',form);await client.invalidateQueries({queryKey:['references']});onSelect(row.id);setFile(null);toast.success('Reference cached with provenance');}catch(e){setError((e as Error).message);}finally{setUploading(false);}};
  const autoFetch=async()=>{const hasLat=lat.trim()!=='';const hasLon=lon.trim()!=='';if(hasLat!==hasLon){setError('Enter both latitude and longitude, or leave both blank for the best match.');return;}if(hasLat&&(!Number.isFinite(+lat)||!Number.isFinite(+lon))){setError('Enter valid numeric coordinates.');return;}setFetching(true);setError('');setAutoStatus('');try{const query=hasLat?`?latitude=${lat}&longitude=${lon}`:'';const row=await apiPost<ReferenceRecord>(`/catalog/auto-reference${query}`);await client.invalidateQueries({queryKey:['references']});onSelect(row.id);const dist=row.match_distance_deg!=null?` · ${row.match_distance_deg.toFixed(2)}° from centre`:'';setAutoStatus(`${row.from_cache?'Reused cached':'Fetched & cached'} ${row.matched_product_title||'LROC product'}${dist}`);toast.success(row.from_cache?'Reused cached LROC reference (no new request)':'LROC reference fetched & cached for reuse');}catch(e){setError((e as Error).message);}finally{setFetching(false);}};
  const workingBusy=busy||uploading||fetching;
  return <section className="panel-card" data-testid="automatic-reference-panel"><div className="mb-4 flex items-end justify-between"><div><p className="eyebrow" data-testid="reference-eyebrow">02 / REFERENCE</p><h2 className="section-title" data-testid="reference-heading">Fixed reference</h2></div><Link to="/references" className="text-[11px] text-cyan-200" data-testid="browse-reference-library">Library ↗</Link></div>
    <div className="mb-4 rounded-md border border-cyan-500/20 bg-cyan-500/5 p-3" data-testid="auto-reference-fetch">
      <div className="flex items-center gap-2 text-[11px] font-medium text-cyan-200" data-testid="auto-reference-heading"><Satellite size={13}/>Auto-match from LROC</div>
      <p className="mt-1 text-[10px] leading-4 text-slate-400" data-testid="auto-reference-help">A best-match reference is auto-fetched from LROC when you upload a source. Coordinates are optional — enter a target lat/long to refine to a specific region. Results are cached for reuse across sessions.</p>
      <div className="mt-3 grid grid-cols-2 gap-2"><label className="form-field">Latitude ° <span className="text-slate-500">(optional)</span><input value={lat} onChange={e=>setLat(e.target.value)} inputMode="decimal" placeholder="−90 to 90" disabled={workingBusy} data-testid="auto-reference-latitude-input"/></label><label className="form-field">Longitude ° <span className="text-slate-500">(optional)</span><input value={lon} onChange={e=>setLon(e.target.value)} inputMode="decimal" placeholder="−180 to 180" disabled={workingBusy} data-testid="auto-reference-longitude-input"/></label></div>
      <Button variant="outline" size="sm" className="mt-3 w-full" onClick={autoFetch} disabled={workingBusy} data-testid="auto-fetch-reference-btn"><Satellite className="mr-2" size={13}/>{fetching?'Matching & fetching…':(lat.trim()||lon.trim())?'Fetch reference for coordinates':'Auto-fetch best match'}</Button>
      {autoStatus&&<p className="mt-2 text-[10px] text-emerald-300" data-testid="auto-reference-status">{autoStatus}</p>}
    </div>
    <label className="form-field">Operator-selected reference<select value={selected} disabled={workingBusy} onChange={e=>onSelect(e.target.value)} data-testid="reference-catalog-select"><option value="">Select a cached reference…</option>{references.data?.map(r=><option key={r.id} value={r.id}>{r.title} · {r.metadata.lunar_georeferencing_valid?'lunar grid':'diagnostic only'}</option>)}</select></label>
    {references.isError&&<p className="research-notice error-notice mt-3" data-testid="reference-list-error">Reference catalog unavailable. No fallback selected.</p>}
    {reference&&<div className="mt-3 flex gap-3" data-testid="selected-reference-summary"><img src={artifactUrl(reference.image_url)} alt={reference.title} className="h-16 w-20 shrink-0 object-contain bg-black" data-testid="selected-reference-preview"/><div className="min-w-0"><p className="break-all text-xs text-slate-200" data-testid="selected-reference-title">{reference.title}</p><p className="mt-1 text-[10px] text-slate-400" data-testid="selected-reference-dimensions">{reference.metadata.width} × {reference.metadata.height} px · band {reference.metadata.selected_band}</p><p className={`mt-1 text-[10px] ${reference.metadata.lunar_georeferencing_valid?'text-emerald-300':'text-amber-200'}`} data-testid="selected-reference-review-status">{reference.status} · {reference.metadata.lunar_georeferencing_valid?'lunar grid verified':'no scientific georeferencing'}</p></div></div>}
    <details className="mt-4 border-t border-slate-800 pt-3" open={!references.data?.length} data-testid="reference-upload-details"><summary className="cursor-pointer text-xs text-cyan-200" data-testid="reference-upload-trigger">Upload a reference product</summary><div className="mt-3 space-y-3"><label className="form-field">Reference file<input type="file" accept=".png,.jpg,.jpeg,.webp,.tif,.tiff" disabled={busy||uploading} onChange={e=>setFile(e.target.files?.[0]||null)} data-testid="reference-image-input"/></label><label className="form-field">Analysis band<input type="number" min={1} max={32} value={band} disabled={uploading} onChange={e=>setBand(+e.target.value)} data-testid="reference-band-input"/></label><label className="form-field">Product ID / provenance<textarea value={provenance} onChange={e=>setProvenance(e.target.value)} maxLength={2000} rows={2} placeholder="Product identifier, provider, processing level…" data-testid="reference-provenance-input"/></label><Button variant="outline" className="w-full" onClick={upload} disabled={!file||provenance.trim().length<5||uploading||busy} data-testid="upload-reference-btn"><Upload className="mr-2" size={14}/>{uploading?'Validating & caching…':'Cache reference'}</Button></div></details>
    {error&&<p className="research-notice error-notice mt-3" role="alert" data-testid="reference-upload-error">{error}</p>}
    <p className="mt-3 text-[10px] leading-5 text-slate-500" data-testid="reference-automation-notice">No location inferred. QuickMap is a viewer; regional retrieval is unverified.</p>
    <a href="https://quickmap.lroc.im-ldi.com/" target="_blank" rel="noreferrer" className="mt-2 inline-flex items-center gap-1 text-[10px] text-cyan-200" data-testid="quickmap-open-link">Open QuickMap <ExternalLink size={10}/></a>
  </section>;
};