import { UploadCloud, Crosshair, Square, Split } from 'lucide-react';
import type { ReactNode } from 'react';
import { Button } from './ui/button';
import { isRunning, type RegistrationResult, type Capabilities } from '../lib/api';
export const SourceControls=({file,onFile,method,setMethod,band,setBand,sensor,setSensor,refine,setRefine,run,onRun,onCompare,onCancel,canRun,busy,capabilities,children}:{file:File|null;onFile:(file?:File)=>void;method:string;setMethod:(value:string)=>void;band:number;setBand:(value:number)=>void;sensor:string;setSensor:(value:string)=>void;refine:boolean;setRefine:(value:boolean)=>void;run:RegistrationResult|null;onRun:()=>void;onCompare:()=>void;onCancel:()=>void;canRun:boolean;busy:boolean;capabilities?:Capabilities;children?:ReactNode})=><>
  <section className="panel-card" data-testid="source-upload-panel"><p className="eyebrow" data-testid="source-eyebrow">01 / INPUT</p><h2 className="section-title mb-4" data-testid="source-frame-heading">Source frame</h2><label className="upload-dropzone" data-testid="source-image-upload-dropzone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy)onFile(e.dataTransfer.files[0]);}}><input type="file" className="sr-only" accept=".png,.jpg,.jpeg,.tif,.tiff,.webp" disabled={busy} onChange={e=>onFile(e.target.files?.[0])} data-testid="source-image-input"/><div className="flex max-w-full flex-col items-center gap-3 text-center"><UploadCloud className="text-cyan-300" size={26}/><p className="max-w-full break-all text-sm text-slate-200" data-testid="source-upload-label">{file?.name||'Drop source image here'}</p><p className="text-xs text-slate-500" data-testid="source-upload-help">PNG · JPEG · WebP · preprocessed TIFF<br/>{capabilities?`Up to ${capabilities.max_upload_mib} MiB · ${capabilities.max_pixels/1e6} MP`:'Loading processing limits…'}</p><span className="text-xs text-cyan-200" data-testid="source-browse-label">Browse local frame</span></div></label>
  <div className="mt-4 grid grid-cols-[1fr_80px] gap-3"><label className="form-field">Source sensor<select value={sensor} onChange={e=>setSensor(e.target.value)} disabled={busy} data-testid="source-sensor-select"><option value="optical">Preprocessed optical</option><option value="ohrc">OHRC · unverified</option><option value="tmc2">TMC-2 · unverified</option><option value="iirs">IIRS · diagnostic only</option></select></label><label className="form-field">Band<input type="number" min={1} max={32} value={band} disabled={busy} onChange={e=>setBand(+e.target.value)} data-testid="source-band-input"/></label></div></section>
  {children}
  <section className="panel-card" data-testid="alignment-controls-panel"><p className="eyebrow" data-testid="align-eyebrow">03 / REGISTER</p><h2 className="section-title mb-4" data-testid="alignment-controls-heading">Registration controls</h2><label className="form-field">Feature strategy<select value={method} disabled={busy} onChange={e=>setMethod(e.target.value)} data-testid="feature-method-select"><option value="auto">SIFT · ORB fallback</option><option value="sift">SIFT</option><option value="orb">ORB</option></select></label><label className="mt-4 flex items-center justify-between text-xs text-slate-300" data-testid="refinement-status-label">Guarded ECC refinement<input type="checkbox" checked={refine} disabled={busy} onChange={e=>setRefine(e.target.checked)} data-testid="subpixel-refine-trigger-btn"/></label><Button className="mt-5 w-full bg-amber-300 text-slate-950 hover:bg-amber-200" onClick={onRun} disabled={!canRun||busy} data-testid="run-registration-btn"><Crosshair className="mr-2" size={15}/>{busy?'Processing…':'Run registration'}</Button><Button variant="outline" className="mt-2 w-full" onClick={onCompare} disabled={!canRun||busy} data-testid="compare-engines-btn"><Split className="mr-2" size={15}/>Compare SIFT / ORB</Button>
  {isRunning(run)&&<div className="mt-4" data-testid="job-progress-panel"><div className="flex justify-between text-xs text-slate-300" data-testid="job-stage"><span>{run!.stage}</span><span>{run!.progress}%</span></div><progress max={100} value={run!.progress} className="mt-2 h-1.5 w-full accent-cyan-300" data-testid="job-progress"/><Button size="sm" variant="outline" className="mt-3 w-full" onClick={onCancel} data-testid="cancel-job-btn"><Square size={12} className="mr-2"/>Cancel run</Button></div>}
  <p className="mt-3 text-[10px] leading-5 text-slate-500" data-testid="registration-engine-note">{capabilities?`${capabilities.max_active_jobs} worker · ${capabilities.max_queued_jobs} queued · ${capabilities.max_job_seconds} s processing limit`:'Processing limits pending'}<br/>Raw sensor products and orthorectification unsupported.</p></section>
</>;