import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { ExternalLink, Download, Database, RefreshCw, Trash2 } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '../components/ui/button';
import { apiGet, apiPost, apiDelete, artifactUrl, type CatalogItem, type ReferenceRecord, type CoordinateMatch } from '../lib/api';
export default function ReferenceLibrary({onSelect}:{onSelect:(id:string)=>void}){
 const client=useQueryClient();const [filter,setFilter]=useState('');const [latitude,setLatitude]=useState('');const [longitude,setLongitude]=useState('');const [matches,setMatches]=useState<CoordinateMatch[]|null>(null);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [providers,setProviders]=useState<{name:string;reachable:boolean;checked_at:string}[]>([]);
 const catalog=useQuery({queryKey:['catalog'],queryFn:()=>apiGet<CatalogItem[]>('/catalog')});const references=useQuery({queryKey:['references'],queryFn:()=>apiGet<ReferenceRecord[]>('/catalog/references')});
 const act=async(id:string,fn:()=>Promise<void>)=>{setBusy(id);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy('');}};
 const cache=(id:string,cached=false)=>act(id,async()=>{const ref=await apiPost<ReferenceRecord>(`/catalog/context/${id}?use_cache=${cached}`);await client.invalidateQueries({queryKey:['references']});onSelect(ref.id);toast.info(cached?'Cached context selected · diagnostic only':'Context preview cached · diagnostic only');});
 const search=()=>act('search',async()=>{if(latitude.trim()===''||longitude.trim()===''||!Number.isFinite(+latitude)||!Number.isFinite(+longitude))throw new Error('Enter a valid latitude and longitude.');setMatches(await apiGet<CoordinateMatch[]>(`/catalog/search?latitude=${latitude}&longitude=${longitude}`));});
 const products=(matches?matches.map(m=>m.item):catalog.data||[]).filter(item=>`${item.title} ${item.product_id}`.toLowerCase().includes(filter.toLowerCase()));
 return <section data-testid="reference-library-page"><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow" data-testid="library-eyebrow">REFERENCE LIBRARY</p><h1 className="mt-2 text-3xl font-medium" data-testid="library-title">Reference products & provenance</h1></div><Button variant="outline" size="sm" disabled={!!busy} onClick={()=>act('provider',async()=>setProviders(await apiPost('/catalog/provider-check')))} data-testid="provider-check-btn"><RefreshCw size={14} className="mr-2"/>{busy==='provider'?'Checking access…':'Check provider access'}</Button></div>
 <p className="research-notice" data-testid="provider-automation-notice">QuickMap is a viewer. LROC Downloads supplies curated products, not arbitrary-region retrieval. Context previews cannot supply scientific georeferencing.</p>
 {providers.length>0&&<div className="mt-3 flex flex-wrap gap-4" data-testid="provider-status-results">{providers.map((p,i)=><p key={p.name} className="text-xs text-slate-400" data-testid={`provider-status-${i}`}>{p.name}: <span className={p.reachable?'text-emerald-300':'text-rose-300'}>{p.reachable?'page reachable':'unavailable'}</span> · regional API unverified · {new Date(p.checked_at).toLocaleTimeString()}</p>)}</div>}
 {error&&<p className="research-notice error-notice mt-4" role="alert" data-testid="library-error">{error}</p>}
 <section className="mt-7" data-testid="cached-references-section"><h2 className="section-title mb-3" data-testid="cached-references-title">Cached operator references</h2>{references.data?.length?<div className="grid grid-cols-1 gap-4 lg:grid-cols-3">{references.data.map(ref=><article key={ref.id} className="catalog-card p-4" data-testid={`cached-reference-${ref.id}`}><div className="flex gap-3"><img src={artifactUrl(ref.image_url)} alt={ref.title} className="h-20 w-24 shrink-0 bg-black object-contain" data-testid={`cached-reference-image-${ref.id}`}/><div className="min-w-0"><p className="break-all text-sm text-slate-200" data-testid={`cached-reference-title-${ref.id}`}>{ref.title}</p><p className="mt-1 text-[10px] text-slate-400" data-testid={`cached-reference-status-${ref.id}`}>{ref.status} · {ref.metadata.width} × {ref.metadata.height} px</p><p className="mt-1 text-[10px] text-amber-200" data-testid={`cached-reference-georef-${ref.id}`}>{ref.metadata.lunar_georeferencing_valid?'Verified local lunar grid':'Diagnostic only'}</p></div></div><p className="mt-3 break-all text-[10px] leading-5 text-slate-500" data-testid={`cached-reference-provenance-${ref.id}`}>{ref.provenance}</p><p className="mt-2 break-all font-mono text-[9px] text-slate-500" data-testid={`cached-reference-hash-${ref.id}`}>SHA-256 {ref.sha256}</p><div className="mt-3 flex justify-between"><Button size="sm" variant="outline" onClick={()=>onSelect(ref.id)} data-testid={`select-reference-${ref.id}`}>Select reference</Button><Button size="icon" variant="ghost" aria-label={`Remove ${ref.title}`} disabled={!!busy} onClick={()=>{if(window.confirm('Remove cached reference? Stored objects are soft-deleted, not physically erased.'))act(ref.id,async()=>{await apiDelete(`/catalog/references/${ref.id}`);await client.invalidateQueries({queryKey:['references']});});}} data-testid={`delete-reference-${ref.id}`}><Trash2 size={14}/></Button></div></article>)}</div>:<p className="border-y border-slate-800 py-5 text-xs text-slate-500" data-testid="references-empty">No references cached. Upload a reference in the workspace.</p>}</section>
 <div className="mt-8 flex flex-wrap items-end justify-between gap-4 border-t border-slate-800 pt-6"><div><h2 className="section-title" data-testid="curated-products-title">LROC curated context</h2><p className="mt-1 text-xs text-slate-500" data-testid="curated-products-note">Inherited descriptive bounds · pixel footprints unverified</p></div><label className="form-field">Filter products<input value={filter} onChange={e=>setFilter(e.target.value)} data-testid="catalog-search-input"/></label></div>
 <div className="my-5 flex flex-wrap items-end gap-3"><label className="form-field max-w-32">Latitude °<input value={latitude} onChange={e=>setLatitude(e.target.value)} inputMode="decimal" placeholder="−90 to 90" data-testid="latitude-input"/></label><label className="form-field max-w-32">Longitude °<input value={longitude} onChange={e=>setLongitude(e.target.value)} inputMode="decimal" placeholder="−180 to 180" data-testid="longitude-input"/></label><Button variant="outline" size="sm" disabled={!!busy} onClick={search} data-testid="coordinate-search-btn">Find context regions</Button>{matches&&<Button variant="ghost" size="sm" onClick={()=>setMatches(null)} data-testid="clear-coordinate-search">Clear</Button>}</div>
 <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4" data-testid="curated-catalog-grid">{products.map(item=><article className="catalog-card" key={item.id} data-testid={`catalog-card-${item.id}`}><div className="flex aspect-[4/3] items-center justify-center bg-black"><img src={item.image_url} alt={item.title} className="h-full w-full object-contain" data-testid={`catalog-image-${item.id}`}/></div><div className="p-4"><p className="text-[9px] uppercase text-amber-200" data-testid={`catalog-status-${item.id}`}>Context only</p><h3 className="mt-2 text-sm font-medium" data-testid={`catalog-title-${item.id}`}>{item.title}</h3><p className="mt-2 break-all font-mono text-[9px] text-slate-500" data-testid={`catalog-product-${item.id}`}>{item.product_id}</p><p className="mt-2 text-[10px] text-slate-400" data-testid={`catalog-type-${item.id}`}>{item.product_type} · {item.resolution}</p><div className="mt-4 flex flex-wrap gap-2"><Button size="sm" variant="outline" disabled={!!busy} onClick={()=>cache(item.id)} data-testid={`fetch-context-${item.id}`}><Download size={12} className="mr-1"/>{busy===item.id?'Fetching…':'Fetch preview'}</Button><Button size="sm" variant="ghost" disabled={!!busy} onClick={()=>cache(item.id,true)} data-testid={`use-cached-context-${item.id}`}><Database size={12} className="mr-1"/>Cached</Button></div><a href={item.source_url} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-1 text-[10px] text-cyan-200" data-testid={`catalog-source-link-${item.id}`}>Provider product listing <ExternalLink size={10}/></a></div></article>)}</div>{!products.length&&<p className="py-8 text-xs text-slate-500" data-testid="catalog-empty">No context regions found. No reference was substituted.</p>}
 </section>;
}