import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Download, Trash2, FolderOpen } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '../components/ui/button';
import { apiGet,apiDelete,downloadArtifact,format,isRunning,type RegistrationResult } from '../lib/api';
export default function RunHistory({onOpen}:{onOpen:(run:RegistrationResult)=>void}){
 const client=useQueryClient();const query=useQuery({queryKey:['runs'],queryFn:()=>apiGet<RegistrationResult[]>('/registration/runs'),refetchInterval:3000});
 const remove=async(run:RegistrationResult)=>{if(!window.confirm('Remove this run and local cache? Objects in private storage are soft-deleted, not physically erased.'))return;try{await apiDelete(`/registration/runs/${run.id}`);await client.invalidateQueries({queryKey:['runs']});}catch(e){toast.error((e as Error).message);}};
 return <section data-testid="run-history-page"><p className="eyebrow" data-testid="run-history-eyebrow">REPRODUCIBLE RUN RECORDS</p><h1 className="mt-2 text-3xl font-medium" data-testid="run-history-title">Run history</h1><p className="mt-3 text-xs text-slate-500" data-testid="run-history-retention-note">Input checksums, parameters and diagnostics retained. Manual removal uses soft deletion; physical object retention is not configured.</p>{query.isError&&<p className="research-notice error-notice mt-5" data-testid="run-history-error">Run history unavailable.</p>}<div className="mt-7">{query.data?.map(run=><article className="run-row" key={run.id} data-testid={`run-row-${run.id}`}><div><p className="text-sm" data-testid={`run-source-${run.id}`}>{run.source_filename}</p><p className="mt-1 text-[10px] text-slate-500" data-testid={`run-meta-${run.id}`}>{run.id.slice(0,8)} · {new Date(run.generated_at).toLocaleString()} · {run.method||run.requested_method.toUpperCase()}</p></div><div><p className="text-xs text-slate-300" data-testid={`run-reference-${run.id}`}>{run.reference_title}</p><p className="mt-1 text-[10px] text-slate-500" data-testid={`run-rmse-${run.id}`}>Fitting RMSE {format(run.metrics?.rmse,3)} px</p></div><span className={`text-[11px] ${run.status==='completed'?'text-emerald-300':run.status==='failed'?'text-rose-300':'text-amber-200'}`} data-testid={`run-status-${run.id}`}>{run.status} · {run.quality_gate.export_allowed?'export allowed':'export blocked'}</span><div className="flex !flex-none gap-1"><Button size="icon" variant="ghost" title="Open run" aria-label="Open run" onClick={()=>onOpen(run)} data-testid={`open-run-${run.id}`}><FolderOpen size={16}/></Button><Button size="icon" variant="ghost" title="Download diagnostics" aria-label="Download diagnostics" onClick={()=>downloadArtifact(run.report_url,`moon-${run.id}.json`).catch(e=>toast.error(e.message))} data-testid={`download-run-${run.id}`}><Download size={16}/></Button><Button size="icon" variant="ghost" title="Remove run" aria-label="Remove run" disabled={isRunning(run)} onClick={()=>remove(run)} data-testid={`delete-run-${run.id}`}><Trash2 size={15}/></Button></div></article>)}</div>{!query.isLoading&&!query.data?.length&&<p className="border-b border-slate-800 py-12 text-sm text-slate-500" data-testid="run-history-empty">No runs recorded yet.</p>}</section>;
}